# Generated by Django 6.0.2 on 2026-02-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='cursos/')),
                ('cupo_maximo', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_inicio_inscripcion', models.DateField()),
                ('fecha_fin_inscripcion', models.DateField()),
                ('hora_inicio_inscripcion', models.TimeField()),
                ('hora_fin_inscripcion', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('comprobante_subido', 'Comprobante Subido'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('lista_espera', 'Lista de Espera')], default='pendiente', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='web.curso')),
            ],
            options={
                'unique_together': {('curso', 'dni')},
            },
        ),
    ]
