# Generated by Django 6.0.2 on 2026-02-14 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_novedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedad',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='novedad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='novedades/'),
        ),
    ]
