# Generated by Django 6.0.2 on 2026-02-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_contenido_novedad_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='hora_fin_inscripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='hora_inicio_inscripcion',
        ),
    ]
