# Generated by Django 6.0.2 on 2026-02-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_curso_hora_fin_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('proximo', 'Próximamente')], default='cerrado', max_length=20),
        ),
    ]
