# Generated by Django 6.0.2 on 2026-02-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('historia', models.TextField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='nosotros/')),
            ],
        ),
    ]
